const defaultShortcuts = {
	// JS Frameworks & Libraries
	htmx: "https://htmx.org",
	react: "https://react.dev",
	vue: "https://vuejs.org",
	angular: "https://angular.io",
	svelte: "https://svelte.dev",
	nextjs: "https://nextjs.org",
	nuxt: "https://nuxt.com",
	remix: "https://remix.run",
	solidjs: "https://www.solidjs.com",
	alpinejs: "https://alpinejs.dev",
	qwik: "https://qwik.builder.io",
	preact: "https://preactjs.com",
	lit: "https://lit.dev",
	ember: "https://emberjs.com",
	jquery: "https://jquery.com",
	lodash: "https://lodash.com",

	// Static Site Generators
	astro: "https://astro.build",
	eleventy: "https://www.11ty.dev",
	hugo: "https://gohugo.io",
	jekyll: "https://jekyllrb.com",

	// 3D, Animation & Charting
	threejs: "https://threejs.org",
	pixijs: "https://pixijs.com",
	phaser: "https://phaser.io",
	babylonjs: "https://www.babylonjs.com",
	gsap: "https://gsap.com",
	animejs: "https://animejs.com/",
	"framer-motion": "https://www.framer.com/motion/",
	d3: "https://d3js.org",
	chartjs: "https://www.chartjs.org",

	// State Management
	redux: "https://redux.js.org",
	zustand: "https://github.com/pmndrs/zustand",
	pinia: "https://pinia.vuejs.org",
	recoil: "https://recoiljs.org",
	mobx: "https://mobx.js.org",

	// CSS Frameworks & Tools
	tailwind: "https://tailwindcss.com",
	bootstrap: "https://getbootstrap.com",
	bulma: "https://bulma.io",
	foundation: "https://get.foundation",
	materialize: "https://materializecss.com",
	sass: "https://sass-lang.com",
	less: "https://lesscss.org",
	postcss: "https://postcss.org",
	styledcomponents: "https://styled-components.com",
	emotioncss: "https://emotion.sh",
	unocss: "https://unocss.dev",

	// Build Tools & Dev Tools
	vite: "https://vitejs.dev",
	webpack: "https://webpack.js.org",
	rollup: "https://rollupjs.org",
	parcel: "https://parceljs.org",
	esbuild: "https://esbuild.github.io",
	turbo: "https://turbo.build",
	babel: "https://babeljs.io",
	eslint: "https://eslint.org",
	prettier: "https://prettier.io",

	// Testing
	jest: "https://jestjs.io",
	vitest: "https://vitest.dev",
	playwright: "https://playwright.dev",
	cypress: "https://www.cypress.io",
	storybook: "https://storybook.js.org",
	testinglibrary: "https://testing-library.com",

	// Programming Languages
	typescript: "https://www.typescriptlang.org",
	python: "https://www.python.org",
	rust: "https://www.rust-lang.org",
	go: "https://go.dev",
	java: "https://www.java.com",
	csharp: "https://dotnet.microsoft.com/en-us/languages/csharp",
	dotnet: "https://dotnet.microsoft.com",

	// Mobile & Desktop
	reactnative: "https://reactnative.dev",
	flutter: "https://flutter.dev",
	swift: "https://developer.apple.com/swift/",
	kotlin: "https://kotlinlang.org",
	expo: "https://expo.dev",
	electron: "https://www.electronjs.org",
	tauri: "https://tauri.app",

	// Backend Frameworks
	node: "https://nodejs.org",
	deno: "https://deno.com",
	bun: "https://bun.sh",
	expressjs: "https://expressjs.com",
	fastify: "https://fastify.dev",
	nestjs: "https://nestjs.com",
	hono: "https://hono.dev",
	koa: "https://koajs.com",
	django: "https://www.djangoproject.com",
	flask: "https://flask.palletsprojects.com",
	fastapi: "https://fastapi.tiangolo.com",
	laravel: "https://laravel.com",
	symfony: "https://symfony.com",
	rails: "https://rubyonrails.org",
	spring: "https://spring.io",
	gin: "https://gin-gonic.com",
	echo: "https://echo.labstack.com",
	fiber: "https://gofiber.io",

	// APIs & GraphQL
	graphql: "https://graphql.org",
	apollo: "https://www.apollographql.com",
	trpc: "https://trpc.io",
	grpc: "https://grpc.io",
	swagger: "https://swagger.io",
	postman: "https://www.postman.com",
	insomnia: "https://insomnia.rest",
	hoppscotch: "https://hoppscotch.io",

	// Authentication & BaaS
	auth0: "https://auth0.com",
	clerk: "https://clerk.com",
	supabase: "https://supabase.com",
	firebase: "https://firebase.google.com",
	appwrite: "https://appwrite.io",
	betterauth: "https://www.better-auth.com/",

	// CMS & Headless CMS
	strapi: "https://strapi.io",
	sanity: "https://www.sanity.io",
	contentful: "https://www.contentful.com",
	wordpress: "https://wordpress.com",
	medusajs: "https://medusajs.com/",
	directus: "https://directus.io/",
	studiocms: "https://studiocms.dev/",
	ghostcms: "https://ghost.org",

	// Databases & ORMs
	mongodb: "https://www.mongodb.com",
	postgres: "https://www.postgresql.org",
	mysql: "https://www.mysql.com",
	mariadb: "https://mariadb.org",
	sqlite: "https://www.sqlite.org",
	redis: "https://redis.io",
	valkey: "https://valkey.io",
	elasticsearch: "https://www.elastic.co",
	pocketbase: "https://pocketbase.io",
	prisma: "https://www.prisma.io",
	drizzle: "https://orm.drizzle.team",
	typeorm: "https://typeorm.io",
	sequelize: "https://sequelize.org",
	neondb: "https://neon.tech",
	planetscale: "https://planetscale.com",
	turso: "https://turso.tech",

	// Version Control & Git Platforms
	github: "https://github.com",
	gitlab: "https://gitlab.com",
	bitbucket: "https://bitbucket.org",
	codeberg: "https://codeberg.org",
	gitea: "https://about.gitea.com",

	// Cloud & Hosting
	vercel: "https://vercel.com",
	netlify: "https://www.netlify.com",
	railway: "https://railway.app",
	fly: "https://fly.io",
	render: "https://render.com",
	cloudflare: "https://www.cloudflare.com",
	aws: "https://aws.amazon.com",
	azure: "https://azure.microsoft.com",
	gcp: "https://cloud.google.com",
	digitalocean: "https://www.digitalocean.com",
	linode: "https://www.linode.com",
	vultr: "https://www.vultr.com",
	hetzner: "https://www.hetzner.com",

	// DevOps & CI/CD
	docker: "https://www.docker.com",
	kubernetes: "https://kubernetes.io",
	terraform: "https://www.terraform.io",
	ansible: "https://www.ansible.com",
	jenkins: "https://www.jenkins.io",
	githubactions: "https://github.com/features/actions",

	// Code Editors
	vscode: "https://code.visualstudio.com",
	cursor: "https://cursor.sh",
	zed: "https://zed.dev",
	sublime: "https://www.sublimetext.com",
	neovim: "https://neovim.io",

	// Package Managers
	npm: "https://www.npmjs.com",
	yarn: "https://yarnpkg.com",
	pnpm: "https://pnpm.io",
	pip: "https://pip.pypa.io",
	pypi: "https://pypi.org",
	cargo: "https://crates.io",
	composer: "https://getcomposer.org",
	homebrew: "https://brew.sh",

	// Documentation & Learning
	mdn: "https://developer.mozilla.org",
	w3schools: "https://www.w3schools.com",
	stackoverflow: "https://stackoverflow.com",
	devdocs: "https://devdocs.io",
	caniuse: "https://caniuse.com",
	regex: "https://regex101.com",

	// Code Playgrounds
	codepen: "https://codepen.io",
	codesandbox: "https://codesandbox.io",
	stackblitz: "https://stackblitz.com",
	jsfiddle: "https://jsfiddle.net",
	replit: "https://replit.com",
	glitch: "https://glitch.com",

	// Productivity & Communication
	gmail: "https://mail.google.com",
	outlook: "https://outlook.live.com",
	protonmail: "https://proton.me/mail",
	gcalendar: "https://calendar.google.com",
	gdrive: "https://drive.google.com",
	dropbox: "https://www.dropbox.com",
	notion: "https://www.notion.so",
	obsidian: "https://obsidian.md",
	logseq: "https://logseq.com",
	todoist: "https://todoist.com",
	trello: "https://trello.com",
	asana: "https://asana.com",
	linear: "https://linear.app",
	jira: "https://www.atlassian.com/software/jira",
	slack: "https://slack.com",
	discord: "https://discord.com",
	telegram: "https://telegram.org",
	whatsapp: "https://www.whatsapp.com",
	zoom: "https://zoom.us",
	meet: "https://meet.google.com",
	teams: "https://teams.microsoft.com",

	// Social Media
	twitter: "https://twitter.com",
	x: "https://twitter.com",
	bluesky: "https://bsky.app",
	mastodon: "https://joinmastodon.org",
	threads: "https://www.threads.net",
	linkedin: "https://www.linkedin.com",
	facebook: "https://www.facebook.com",
	instagram: "https://www.instagram.com",
	tiktok: "https://www.tiktok.com",
	snapchat: "https://www.snapchat.com",
	reddit: "https://www.reddit.com",
	youtube: "https://www.youtube.com",
	twitch: "https://www.twitch.tv",
	medium: "https://medium.com",
	substack: "https://substack.com",
	dev: "https://dev.to",
	hashnode: "https://hashnode.com",

	// Design & Creative
	figma: "https://www.figma.com",
	sketch: "https://www.sketch.com",
	framer: "https://www.framer.com",
	canva: "https://www.canva.com",
	photopea: "https://www.photopea.com",
	blender: "https://www.blender.org",
	dribbble: "https://dribbble.com",
	behance: "https://www.behance.net",
	awwwards: "https://www.awwwards.com",
	unsplash: "https://unsplash.com",
	pexels: "https://www.pexels.com",
	lucide: "https://lucide.dev",
	heroicons: "https://heroicons.com",
	flaticon: "https://www.flaticon.com",
	fontawesome: "https://fontawesome.com",
	"google-fonts": "https://fonts.google.com",
	coolors: "https://coolors.co",
	"radix-colors": "https://www.radix-ui.com/colors",

	// AI & Machine Learning
	chatgpt: "https://chat.openai.com",
	claude: "https://claude.ai",
	gemini: "https://gemini.google.com",
	perplexity: "https://www.perplexity.ai",
	poe: "https://poe.com",
	midjourney: "https://www.midjourney.com",
	huggingface: "https://huggingface.co",
	replicate: "https://replicate.com",
	openai: "https://openai.com",
	anthropic: "https://www.anthropic.com",
	tensorflow: "https://www.tensorflow.org",
	pytorch: "https://pytorch.org",
	kaggle: "https://www.kaggle.com",
	arxiv: "https://arxiv.org",

	// News & Information
	wikipedia: "https://www.wikipedia.org",
	hackernews: "https://news.ycombinator.com",
	hn: "https://news.ycombinator.com",
	producthunt: "https://www.producthunt.com",
	indiehackers: "https://www.indiehackers.com",

	// Shopping & E-commerce
	amazon: "https://www.amazon.com",
	ebay: "https://www.ebay.com",
	etsy: "https://www.etsy.com",
	aliexpress: "https://www.aliexpress.com",

	// Entertainment & Streaming
	netflix: "https://www.netflix.com",
	spotify: "https://www.spotify.com",
	soundcloud: "https://soundcloud.com",
	imdb: "https://www.imdb.com",
	letterboxd: "https://letterboxd.com",
	goodreads: "https://www.goodreads.com",
	steam: "https://store.steampowered.com",

	// Finance & Crypto
	coinmarketcap: "https://coinmarketcap.com",
	coingecko: "https://www.coingecko.com",
	binance: "https://www.binance.com",
	coinbase: "https://www.coinbase.com",
	paypal: "https://www.paypal.com",
	stripe: "https://stripe.com",
	tradingview: "https://www.tradingview.com",

	// Education & Learning
	coursera: "https://www.coursera.org",
	udemy: "https://www.udemy.com",
	edx: "https://www.edx.org",
	khan: "https://www.khanacademy.org",
	freecodecamp: "https://www.freecodecamp.org",
	leetcode: "https://leetcode.com",
	hackerrank: "https://www.hackerrank.com",
	codewars: "https://www.codewars.com",

	// Travel
	flights: "https://www.google.com/flights",
	airbnb: "https://www.airbnb.com",
	booking: "https://www.booking.com",
	gmaps: "https://maps.google.com",

	// Utilities

	google: "https://google.com",
	duckduckgo: "https://duckduckgo.com",
	bing: "https://www.bing.com",
	translate: "https://translate.google.com",
	weather: "https://weather.com",
	speedtest: "https://www.speedtest.net",
};
